[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
n3_hello_world = "2zz4zSSMVPc291qsiYtDdRDENXqJgmRhzmVX4WEm5Bh6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Farasat\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
